# ***Array Creation methods***

### *Creating NumPy Arrays*

- Arrays can be created using 
    - array(), 
    - zeros(), 
    - ones(), 
    - arange(), 
    - linspace().

In [1]:
import numpy as np

In [2]:
# using array()
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [8]:
# using zeros()
arr1 = np.zeros(2, dtype=int)
arr1

array([0, 0])

In [7]:
arr2 = np.zeros((2,3), dtype=int)
arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
# using ones()
arr3 = np.ones((3,4), dtype=int)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
# using arange()
arr4 = np.arange(5,15,2)
arr4

array([ 5,  7,  9, 11, 13])

In [ ]:
# using linspace()
arr5 = np.linspace(0,21,6)          # evenly spaced values
arr5

array([ 0. ,  4.2,  8.4, 12.6, 16.8, 21. ])